[package]
name = "election_result_process"
version = "0.1.0"
authors = ["Tarin Mahmood <tmahmood@democracyinternational.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.1"
regex = "1"
